name: EAS Update
on:
  push:
    branches:
     - main

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Fetch Pull Request Title
      id: pr_title  # We'll use this ID to reference the output of this step
      run: |
        PR_TITLE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" \
                        -H "Accept: application/vnd.github+json" \
                        | jq -r '.[0].title')
        echo "::set-output name=title::$PR_TITLE"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run EAS Update
        # uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --branch preview -message "${{ steps.pr_title.outputs.title }}" --non-interactive